apiVersion: v1
kind: ConfigMap
metadata:
  name: anubis
  namespace: forgejo
data:
  botPolicy.yaml: |
    bots:
      - import: (data)/meta/default-config.yaml

      - name: UptimeKuma
        user_agent_regex: UptimeKuma/09e0d572-d073-4595-8f68-60372ded739d
        action: ALLOW

    status_codes:
      CHALLENGE: 403
      DENY: 403
