apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml
  - db.yaml
  - cache
  - signing-key.yaml
  - security-config.yaml
  - anubis-config.yaml
  - app.yaml
  - ingress.yaml
  - networkpolicy.yaml
  - certificate.yaml
  - certificate-old.yaml
