apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: security-config
  namespace: forgejo
spec:
  encryptedData:
    internal-token: AgDfmfgmn3C0vy+wai73hO2flKVTzWBAvdknWDDd+pHGw+VNAOfU4YRew7GCKmjYJLca1Yw6natCRKJpq9NNq8I22Ox9pHMubjFMCgF5hBet+NfPoUzk0i3s+Ha8C8fQ/qzuSH4JT5wvRAdfi+lnNjrpRgu/4fYvIVULwNcm1vagFLfT5ftLICPPhuIl5dgCwelY/ghi66Zpuadj/vIInEhajfwb1EyIFG6GxhiecyxIMUwDC5LGSil60+6pRkviR6k7LwNEY6mrTXdCohAjxG7bnePzwBhbfdth/+gOuoWxmAHvM/+vZFfs3vVRt7hFEjPHVsScakyIJBxh99AGuy+kpiLR1sJmocXHZ58UyEICsSgStHSc1vzE+itXfsIpMDd5E63KJOrhcaYm5Yl5fj33j/MZXQ1B7/Gz2teGpo+mle/CYjd12fkdTCkYENWgTOcgh/ckID7Y9Vw1ReetxwLVtZtR1r92fzIt01kYbgzhCjPdsK+z0mJfKDaga9pTryAh4a2I38lssI6AoKiavf7dKpNd9oNBwKhuCsOLih066KpZE7Ti3aXlGOtHQ0AKKKGXcItyEM8jiPGdLOG9ed75RBdQxDOAP241OD4mhFtg/DiLu6ihSePS2Kh0XwsDil7Aw8LEzeGulOxTxJLNtGP72Qsfm7PfwhaXXJKkCQiL3vh21idhxHdrIC5QSevsKh8MS7HhP/GOOmaJkEJIFOYSs/DeW5pxqkIlCUjCZtbMnNP41fY+Nty/q8f7Oh6Zzk3LCB58ZSqPtfqwj3BtTNcWGFWbB1nzLnKQQVTzioP0dXL1UUkWAst8PkvaH8g7/eNpaA+gkTFFqfs=
  template:
    metadata:
      name: security-config
      namespace: forgejo
