apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: signing-key
  namespace: forgejo
spec:
  encryptedData:
    privateKey: AgBuNjkB+dp+aYKcm7tZ1sfrKm/DN8UJ6NkaK14yuOokVVbzqL15cf07GSLs3brF8kB0t6kviXYyNHUJMuHdhco/Pl/uX0P5fTvlDrOh9mGIn65A4c0VghKAtILsEDJ+X2xWnM0ReqMeGPb7jDd9j0wTBVGve0dSgrpV+89figdG3+boI71HSiOYVosN4ZEtfKd+5CrCYv5A1F7y3eTnGDLeX6g2rxYMyIO3wGqxCIxXTUpSdD14wBBxNUdiO7I0/ch/YBKwEELU4zvbk9ypnl6CWNkcPVdIXUsji1dbzXg+QS8PVCp2P/AE+u7Dnq/+CxCfQGkGeyoYhuKNISrLSqQjsLSLvLnru/1g6+kjyAu4KNivuFBhsbkTPMw4kkDEY63f/qcbszmsNqchWB+UjRuYDtE4htiljFransRwkvqwskrIWuCPKObxv32JLf7Ny74rwdHPCfNa52R0PYPYxXUDZoK5gGkmN6oOYLiDf5a7//OfhCcm7iWXF+2qEUY4HbJXQTMAPRflsz+GLqTKre5TBncH713iI/oOaUDaNqxEDTZH0sAwMhQEZacm2Ore3/L5MDsslB94+xIVcgi3bX3JyGW1pJEXf3vKo9/+3J/tiYW/NZ60cCLNjgT87+aEsPbaL73GsoyERgs43HdtMLJ8iILuzcq1Dm/Icu2w2blonHTJix+2eLIeRBbEm+H2lDULIXeWisQgRQzy/+TmhUMMjOmSNsJrTSE/wFFsG7mtb8tz3F5tJxM8FUMxWvo0D1s25PDWRge+Visf7rjdYbD5h09F+4i3O6SNo72X2PSzacLbjy/Gr3/c3XWBzmhafLzz2DOGgnmHnSVkQg20xUd/MXpNAmfXi6Zg+ZqEPXEmEMMY28zsl3irsm8YztOFJZ/Trq/1FXWyH5aBrNY7hCLlR5auI0OIvcN/K5dukHsDpg1xiNlJx9Zyaz4QK/kxAkjFgHIte2T5LyrCQnyaoZTvW0cSG+/0i9eM+14VPN8DfCPvVo1Jh7TvBOWgFr3RNnNGYx+drTHyZOxzLOBr51+vom88Y6MEdaWVSMxd3JgFfD7nNLJX68o7Kbt2DkWxbjPXfQ06Vabx0R31KQk5Wm6sk4+BALbQUoLW0mD7WtJ/SylmQVsaodcnWxH85qchFLT2+epoN2PCJtcuR41tSHGEfrGXbJbN8a5KoeX/z5W07Xk9wxVr6H9GKDC/PkL9YB5I0b8YA9Mg9vJ2nXyPjg+UZTqFyBWFoX1ktGw=
  template:
    metadata:
      name: signing-key
      namespace: forgejo
