apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate
  namespace: renovate
data:
  config.js: |
    module.exports = {
            platform: 'forgejo',
            endpoint: 'https://forge.mohsun.az/api/v1/',
            gitAuthor: 'renovate[bot] <renovate-bot@forge.mohsun.az>',
            repositories: [
                    'mohsunb/self-hosted',
            ],
            onboarding: true,
            onboardingConfig: {
                    $schema: 'https://docs.renovatebot.com/renovate-schema.json',
                    extends: [
                            'config:recommended',
                            ':semanticCommits',
                    ],
            },
            autodiscover: false,
    };
