apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
  namespace: renovate
spec:
  schedule: "0 * * * *"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 10
  successfulJobsHistoryLimit: 1
  startingDeadlineSeconds: 300
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          volumes:
            - name: config
              configMap:
                name: renovate
          containers:
            - name: renovate
              image: docker.io/renovate/renovate:43.180.3
              envFrom:
                - secretRef:
                    name: renovate
              volumeMounts:
                - name: config
                  mountPath: /usr/src/app/config.js
                  subPath: config.js
                  readOnly: true
          restartPolicy: Never
