apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: immich
  namespace: immich
spec:
  secretName: gallery-mohsun-az-tls
  dnsNames:
    - "gallery.mohsun.az"
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
