apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: library
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-retain
  resources:
    requests:
      storage: 100Gi
