apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  secretName: sync-mohsun-az-tls
  dnsNames:
    - "sync.mohsun.az"
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
