apiVersion: apps/v1
kind: Deployment
metadata:
  name: bridge
  namespace: forgejo
spec:
  selector:
    matchLabels:
      app: bridge
  template:
    metadata:
      labels:
        app: bridge
    spec:
      containers:
        - name: bridge
          image: forge.mohsun.az/mohsunb/forgejo-ntfy-bridge:0.2.0
          env:
            - name: NTFY_URL
              value: https://push.mohsun.az
            - name: BLACKLISTED_USER
              value: mohsunb
            - name: NTFY_TOPIC
              valueFrom:
                secretKeyRef:
                  name: ntfy-config
                  key: topic
          ports:
            - containerPort: 8080
          startupProbe:
            httpGet:
              path: /livez
              port: 8080
            periodSeconds: 10
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /livez
              port: 8080
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
