apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: forgejo-runner
  namespace: argocd
spec:
  project: default
  source:
    chart: forgejo-runner
    repoURL: codeberg.org/wrenix/helm-charts
    targetRevision: 0.7.6
    helm:
      releaseName: forgejo-runner
      valuesObject:
        knownLastVersion: true
        runner:
          config:
            instance: https://forge.mohsun.az
            name: main-runner
            # NOTE: this is for testing purposes
            # TODO: delete in production
            token: 82b40e3fb8efbf5dc3fab890fc08d9862be6eee0
  destination:
    server: https://kubernetes.default.svc
    namespace: forgejo
  syncPolicy:
    automated:
      enabled: true
