apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd/cnpg
    repoURL: https://github.com/mohsunb/self-hosted.git
    targetRevision: main
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
    automated:
      enabled: true
