apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd/sealed-secrets
    repoURL: https://github.com/mohsunb/self-hosted.git
    targetRevision: main
  syncPolicy:
    automated:
      enabled: true
