apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: server-config
  namespace: invidious
spec:
  encryptedData:
    INVIDIOUS_CONFIG: AgCsfIhW6CQRu429Tx5n02xo4eC9jLTHa9+4GTbXVwq/3P7BKWo54aiNb+oB0rRrf80rSe4fkjcJ/ycxh1lMzbEcfN+3gjqGtURDrSDxZhCMCQPc7URi2uL0AD6ZDC5Ec4dIyFBmMS+7yFl0C9WkRksTLQ27sePjEd6YmWfI9aoSi0JpxbMgYgYLktsLVjnQstBCjsl3jRaHIV1Ebbueu+i9asc4M1o3seIwQJVXXW/q9e3OmtMXLnLXZUYwxyATwuvARIxcCNbQO7mNT/CKZRWKg6qmB11BPejZNWMbo9VZzS9awD3CMFZh6grJe6IiltyKw/0oxWXtzjlH5X7Gjp03F3lU97oRTfjXTAfBgTfShw7qZ6PiebYDbtEaKQypOV/dYo1NAjXBaqafiiILeirO6u4agApoOulgj5fXabi2pvLkmf3F8Yuu2Dkc5SM5KOmekUr81UVPTICfDxswB/P9nv7sLhykCXj9g6zs2anZmyHD5eOUd1qG5qmvOfiJgx6P8bhpiatXYbzhorgBzyMPk6nbONdRpHfZ9FA3G7Cv2vhWZT8Ry5bEB2F5XxoPXoa+i7QGIA5wYPsrvze2C94T/lS0D9WuNyOFUW5FCgSRXVT23b6aBwI4hqr3yQovG/1N53JcAaoPwRA0mpot1Qd1I2nuCRstuKNteZUHWzjzaS4K3f+Gplz+a3WapnvIvggjZFvbkarH7Cs4mIVJ7BMqvUbUJi91nUhdiPjbAqMsdifzTMc41400fAVUfDl57lZijTrolbtkn++XmitTkEuDstSAl3KDrRfFAygGa+ZwaZfMb5mwV6x8XEqdkLuzul9xf66uVO35fsP6UFWonddXUkJQmsX96T6uytJ455ZN3WzTOSKpBQiBKUaTIvhr7TZXFIf4V+yZK9rLaG54+QYXEv1n4tIjRJi3J7zMtAB+3Z+WZZ2PDTXGZP7NtVQAr2AoH5HJVwj7RsGYuiSq50dWBP6+zkGecbG5wPk99gbTjSSRdG/r46SzxJBC+KVqsojNVr5nFrgT6GnThQzhbILi7wv7P3BLkZ8WZTM5WS6Tw0s049ph9wlBEWQRjJUVK1SSmKcERJ985LT4WYu4bJNZJk2xH8HfCSDOje3Aj8l4Vw6im9SCdZseHukSqGJJqaA0QqiRlwL+F3NcWuKHzVKJ2fAQe5AXedM7/zK3y/o=
  template:
    metadata:
      name: server-config
      namespace: invidious
