apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: server-config
  namespace: invidious
spec:
  encryptedData:
    INVIDIOUS_CONFIG: AgCnqU2Cst+OimVwJJLMj4lqOtwpo7e0GwWxrOa9QfqBK9IBLpeqvZykipz5na7dlcRTa/oW2BqBTxc0A+zQZmVoTVXL4mbf6/RFGRm6++h1gnPfs1TVdS1r5QAhulMeZb0z4+R6Xd929T1NkyOu2uf1pxrxx+rDLvdBoRP7jRCilHIeRIJoaKGbr0GFAyoEMy1WaOW9perXH+XM00P/Tvxx7CHe/aC1n+VlC1ds/5DuI/2SwSegPyqYp1Vwkw9WJ6hi2qA2qk3wI74/OHRCjQnSm44uul+CqUFihvlg64wGdH9piLNwYzKVis6hTnBXmIoRS0BrkZiz6QINCvT3vJFjc+vC4TDsYWkfF+j2EVRhnF5k7GflxYDxJjTUiOO+5bCD5SOqQzV0hjM6MyzCoD3EQRJDzrZmdUHnLPn8vU0NJTSwzBejTGWHy/dlhXoweGNvWz2tcI9vThJmcIntRt+SyZVBSv8leWnl8q+NgRTTdctG5lO14KQHbzrwiVGW4dlnC0lpqmUt8nRlDpBwH7KTGkrw57/TIJg8Q3cDe16pScegB+aA1OXaWEfaVFcai9Wy8wlpe0O/tzyLHmArbxWe2cHzXgSh9kjAyVNKlDUBy7ceUUQrbnDhIz1FVN6cbWLmWfwg0OGv0MtVFs4X2EMD+tgf2NCJYy75ibfmJr2fZP/IoGJyIqDt+nR2KJ5estnttZmfRPIrb5Ef2F7YMTsEj8jyBEXKnjH1TROXjX929GmtQh/Zg4sQDIvlLmCQNua47TkMq0qIPvxdujElm6gIUjaVlKl1wEzlY6SnEkDouK/hIINnlModG4AWEipR7mrcYAu6RlxXxR8H4adNCDIFOBdaSt5zjXRSNMF3lTlnuUzr1AHHyxscmp6zN46FpYtF/8TaiQnRgEb1owihl0dZNp/T/klIjy+OLRVImBtro91xtyru892GtAZcalGqJPgYIR4LYJZuYBWmmO0rVjKWxDHQvYD+3T+mNo+a9YQbufgAu6GhsZaLnMz3pnON8bwleHCejmWDoaKwd3a5alydiPKL9ghMEuKMgeVrlQNysTItbjtMcp61jU1cvZW2GBfk3F6zhPVqeLadxWbthIMUrY1FQ1UwcESW2i96j8m+PbjCJr4N2YUC+ps4gmR7n3QnhTiGBxT6A8ptuGs1EZxbGuiOyY6bcZfd7o2Qa0bf50LplLuiU6jrFmiXPTjs1s7yA/5U14ngSuJBrWhjxgNNli02vT7yvkX6p7NXntr02pmqvda9QA==
  template:
    metadata:
      name: server-config
      namespace: invidious
