apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: fmd
  namespace: fmd
spec:
  secretName: track-mohsun-az-tls
  dnsNames:
    - "track.mohsun.az"
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
