apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vapid
  namespace: mollysocket
spec:
  encryptedData:
    MOLLY_VAPID_PRIVKEY: AgCN/92ZP2BfpYiwlyoProGM0AN97y2cmfL9AijkZVEflpmpDrjNAHgdDWzQv/e1gf6viiHNEhsR5Mn8OFhqsjlRdZrX5YSesAEmvntSbPvPOOmUACXWAaQ2DztZgTz5LOSQHEEmnLIr+viRzSPF1JDbLwRwOSLnVxejlN5RbvJ7AIO/HjNWABsFuktdC5XnqNMMBU0pkbhnuFpiW1nBigKdjfd9+lGRJUr4druXXlbphmB0HMIhacKEy1N151eQg+/yatTMh7MNUufsrrZ7ylIqeiOuauMFirwTf4K0BRt2kLpPLPBWMZFOPLP3BPlCJdNXdURTczSqJaYskIMTJo51XqloK1f5ovUwBo1aFU1jj8juxWXsqGP/WBp5l+dJps7Ihfa7jSAKqYTDP02DKoEFJCQqPORkf+ACDiLrXBX0DyxZvMXkJIzWjKxo1n/bh6A3tjX2d49OAtfVDvUogR4zBf4ri/g+cpZRCl//LtR53c/dac7MwBbTv6BgMtfP1ddoC5Z1F/v6HHtmpBEcKPahAZaNXw77ko+RXCvRMVJ2SP9mxqFyP0bpRpqLxsrxe2zBBrUWbNHZt+kqZ4xvxQW3ziGHxC8sEeZ3hCzIb/0itDKegDdDHKX1xjuKLJ2Zo9/LH3dDXXYLQulrYJycXuB+uXKhQc11XGYj22HxFGW0cTTkzNzY3hG4k8Hv6VNY1dYXnbh1X4A6YDna8jfNeLPkbkpqatqQEeZmBzewX4CuNR8IYfHKcXaExMOP
  template:
    metadata:
      name: vapid
      namespace: mollysocket
