apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: database
  namespace: vaultwarden
spec:
  instances: 1
  storage:
    size: 128Mi
  bootstrap:
    initdb:
      database: vaultwarden
      owner: vaultwarden
      secret:
        name: database-credentials
