apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: database-credentials
  namespace: vaultwarden
spec:
  encryptedData:
    password: AgCbqq4N+OJn5ApI5/pm4uxF0oHgfKFzsp7U1KchKYJX0QG6UbDcVcx6e2JfGg9cCzilpiHPjjgyoCqoKCywJuxGxXzzdlm90GObxBt6Ve5I4FTKPtq5KFHEsGOgr+Q6WBTuIF5BtdiPjUtYGtiGWQl1c62/p3hg/+JEYlz8+s0x0dca61n2GgVlQSRmxbGhL1n7wIjxztrFe/cvQn1RrlkMjNwDN1FxUCYSZXD06GQl8ZUs4KYhU5RrNf5cYN2KZvHFhjKDAj6PzAMRwk/wCr/EV93bqNTv1WIKAJVkuPy8MMDLkfrV/L7poW97+ZwI3NgrghTBCr2D0xMTFuVWISfZ93fNsozIx/yoK/l0DZER8Md2VA4+MO3IuUvEbbqzduVvaqhHLJ/j0xi9Izcdyyq0D8MBKH+uDDf3l0uP9NYrTUiBEV1u4Q2dv50CqQyLpCgahSmMyRx9dBDMq6ebvywgNONPSw7yId1g1CG2WZdYe0NDHzIhzHtc9ODpxFI7CUqfImVQhIBpnYg/ZY8CZkMMX8ZBO0fr8JPWTcJRhYeyp7fLQtsqOdzADdLjwrrjCqeGBXaSXeMC5Tw5R9lQWjLp+xRSGTxJWAfew5D8VVyNq9MlS+cedv+o3dhF/Fjjj//2yODfR4DWf4bZaSxGMoS0dxeH+Bmeh23lf/zxaSa0UjpVEe9XLPeuoMxRA+X1Ev3foNV7a8SJ6f/qp4nwHUYdK3ZVZqgzKv1CXKOfElFh7CF8Lnr39AVI
    username: AgC/Cx01aS8tWnrmD6GN0Tt8eR0G9QKvMnRE0LCwBsehpAn0lf7F8PDDPrFFsB2EKda9vR6240TRL9fpioE/4jFyuLiPsqR+QlF5dS+lJ5YRbul3z0pXKEBAESGPporTxmmiIo0EWdWPVmWDYRgATgeGjW3Ywj7K2Zz8WWTruz6jbbplwizQ+up6bkL5Ac7rbfQKNWZjiweQMiT+4UIae+8ZvJkjPolsG0CDJn6y3O5wwAShFQR7QIUljWePWehWOMFJ32eKcdrps7TakW9sUxq2vV3MoSbMLWsBhbIzevHcI+6VUaxF8R3PmIO1h8UNSiYvJ+tolBa89aglcNLtj2OCX0EEIrZ94n8vVBp/OLi2Yh5y+FgZm1KsGicr/buBVliOQvW687BlS23c/V3X2Keffbc7uV9sjhjMhiNkRp8tzrC+hhwdwm8FT1kLuuEozrZ65CTOrU0c84YXddLwI0kmw5wMpoRF4u6kY7W8sZwT20ab/1ukYUcVrEOjgl1MgBXjgVu+0ukwyHaAE6+NKnpdmjgRJgucL47RwfhMJnRXqHADbS0JKUYYBSnwoUiv59JvWCDU+KVaI7nw1smEafr4cQRMN9DN9RYQ5D9xUBXJ7ZMmS5HkdGYCGysmR+IKAlHqK6c8UsDVW83GVxLfLf9MFeW6UbJ/XEM1XQD4IlVgsw8gETZXgqhMi6k0n/oMP7nkTL1QdIToezZ/4g==
  template:
    metadata:
      name: database-credentials
      namespace: vaultwarden
    type: kubernetes.io/basic-auth
