apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dns01-issuer-api-token
  namespace: cert-manager
spec:
  encryptedData:
    cloudflare-token: AgB7atv5gv4dXWpyRYlQgGWGRCpwhH5tEN64q8jdeLxYAbTVr6aEU1rPBG2jyoy7ilP2f7p9Rne3GlT/Dooq8OSo7G3PMvnX50WsvqFEWwBH8ylmJ+yXpvIzDRDucDjBR1VYYHonr3yfiRFT95utGfDkc94a5BuuIkBLWRtexRPJMEzX2ptPMDGBKTZA+qEvMFBcI3EXUqDI9qguUOCGXlijMfUnQMlXJpFFuQy1o8I9nf4iqjP6hiA+cAYXw697Vuex7l3qt3wz8QNhMLvxbwBDenkSj0oJvLHt/gmbNJ1IpGyT6L7deClZhDyf+5Bg1TuKiC1Li9kIxapA/Jd9QG1y6sNH6e63gPfS1T9SV6kgJ5z2OwtbPcvAceYgu/80EAuh/89luabtlSg5lswyolCK1r/V0Vn2Z5P3apCpydxNqRmExslBf0exOyNrP9h3vwOwVLNOWOUu3OyokU7UX2LHF4C5Iq0bE1ch3T2nXZlbyQ6/nTS7r+UWQgncy73p9Py/Jc783VbiBZESUk1CvBxDHLgL3V5qr1mhZ+y9v2y8+iPPg2SkL6QfjnQ+VNwrZOaix2ZSetR0HaywPP2Q5rSsP1lrusvpmegL/VnwFeJF3BurawZdYWTeEdkKL2g9SlGLHPNV2jihfkm+K6OJ3RAgZWG64EO02uIDrYkA8iHrNkTNzcrgLcbyP4EQxCheJSRppUuxXSn9GEWI8gzSed77DIAMJK4pD+D5xr1s04JFkG90/xm74/YyJvwX8vf27aQau2Gwmw==
  template:
    metadata:
      name: dns01-issuer-api-token
      namespace: cert-manager
