apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: companion-config
  namespace: invidious
spec:
  encryptedData:
    SERVER_SECRET_KEY: AgCjNcD17JqxfXqNzR0qOjVuhoEC593iALghRnUYfnp3qPrVIihARQWY1UDTxfnH6brhaR/VuDF+uSaHW9vmgiDHh/4eRZutN86LkbRuBtflzMJb0ddmq/TIDkO1YQbc+AaTll0VoGMp3wqU/ICSWDCPECVOEcT98Om2PiB0Zlk+W/tj86tK1Z6pojfJkkXctK2M0CJw3NSYxXEbR8fGq0YfL8Tlu/vo92h1Zlk+8aQpcqaC0ZjLWI4p1ZSEw47chyrP4a5uPkE62EQo8rDZumbboUDelqW8SKgBLn2gsmYkudaTeHIqIZbrx/ES+/zl/V2XDE4GR9v8aR7SbTTd/XMWOcHQTfBNuh0fAB6e2cowupn772ZGdcQplV8m5RDGXn8AgMgkWm3WLhbe+U6mAS3NDbuWSvTjRBcJvTOy5iIfBTegCW5jzRb8zCjeLyFPzdR6UF+Bsh2Dp32AmE85Zg/MU5YN2mwM0sbUctrpzK9k4GGgs2B7PtWu7JF2xEF5FPqiSgNhqtbory8x9s/OAOm6cIfaDdjlH30g4yR7J/SlUrunHu8KbvKi/pIgnyzyfJxWu7RnAgFv4Dc8aREuCS5wrHeIdhMUyEZvqR9q1PBtNFWWcT25tVBoXvUFYReX6w9dVBnswUxCybMqZtUHbfim4oxVJ4VAEfiHDc8qZJQoXg4Boi7l2PCea9i9luIxZafTLCcCnm+/BtJSkSzGbQ6T
  template:
    metadata:
      name: companion-config
      namespace: invidious
