apiVersion: apps/v1
kind: Deployment
metadata:
  name: companion
  namespace: invidious
spec:
  selector:
    matchLabels:
      app: companion
  template:
    metadata:
      labels:
        app: companion
    spec:
      volumes:
        - name: cache
          emptyDir:
            sizeLimit: 10Gi
      containers:
        - name: companion
          image: quay.io/invidious/invidious-companion:latest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: companion-config
          ports:
            - containerPort: 8282
          volumeMounts:
            - name: cache
              mountPath: /var/tmp/youtubei.js
          startupProbe:
            tcpSocket:
              port: 8282
            periodSeconds: 10
            failureThreshold: 30
          livenessProbe:
            tcpSocket:
              port: 8282
            periodSeconds: 10
            failureThreshold: 3
          securityContext:
            capabilities:
              drop: [ALL]
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
