apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: database-credentials
  namespace: invidious
spec:
  encryptedData:
    password: AgAcYElVJcA1xEeD+pOJ9D/Z+y/cpCrzcapxGYpdvCfazdZv5M7MmdsJSqc0+Bwb/5H4gnGyXm5TLJZH/ndlI19F/EOHIZms61PPbW0BIV7mXXr3PLTtr6eI+StatBoOFJZfDoRp5gy5dUwg+t7wMEtadsgrp6NImJJoj1w4eDgWvFS45EjCzXbKHsI8s+p+UDwuEd6Yj1Vvg4Mueo513KtJlyuVw2CpBdErkprKNzaHZVWy63vw35Gg4o3XkV7YKsRwYnIWEEg/nvsDQHUAPaqGbDHyczG53VFmfOTrlvLVqJa2B7bFedFZTaA5BJu4lZlLZHRf56Awt+1Fr98AO/txLJv4im3RDkWIlhV756ugMMa9P8SpYjcoVYFitvTNFFuYHQbKAcjXHECQTiM8CN49R4WFnwgzh7h9lkd/+lLmvwJ3UvmGdJvXY9hT36jgBhRhLJr9wX9D7jhrcQgTbCrbmE+20CycxOt5DzDZai9+C8cyvLJiL1X5kVUf34kHCianbNU2xcg2XGyIhO2+Q1iYZm3X2c8Y7X//gwqSuBn8fRJybEteTtBGTj7KdL/cGgGb5yhZ8xm9CD2v35v7gDjXbUooxv4pfx9dRzS0smnRLoS6vuV2eL9jCZhvukw0qkrci81rABvlWuhi+XJ1+mfTlAhNLKyE3Xn0Buxsh/0ElUQprUR0KrEoBYsNstftyhbjWrI2jL+oSrabVd0rdqKV1HQwSDbfzRt0RpNZtPg=
    username: AgAmg9Bbr1PqvOgJRrBMvYd12bpMIPRgaMhCRV9AIFZYw6R5sbu9BoiyzHITi9Cjo0AAY/ZT6AsmOzjo5OOSpCizvkQJ9LFzcr4o/yB3mb6tpmljyNl2ZY8D/yJLDJhu4iM99WcUsvmSeBXhGZKGySh9sXjfoLLM39PuhWsdxS6+jRrNV41NDZ81DuSvwl/KVL+Wn2CxF7bKTet+/cQA5uxKJNPtWmL6MZBke/0gne7ahLaQfbWUMoc0Z1b6i3nvgUqh3XJXCaZdODK6w/xYKEfvjARZDuC71h7XtyQjUaGl4wYf0Wj1cmk2SKoVfPYBUEH6POxOeArDCBfhTpaJaSGX1NW6eQYoTwbXq7gw8c24+J9TR1NaTeLePKbfJhxG6afosBLft2MFxtP5/iD5dlft/Jnh2HY1EZBcvRSpheA4+1pDrFFsPLJ3aJzzHO2oLC43i/XSCp7+/jNzWWkvpxPyB/rhfemnRzm3ZypnSCnweNkd4XzTFxMiki4jL+InVb1uTGN1UhAkD3inkRFOy5wht2r0cHF79d4CdeoXPzoZXRxaygNfixLntOVtdBQIvtvpsZec7PfbEmyg7H2fYNYFKBYXLeEYnOceXckYV/jq8WyaSjVfHUL2/fprShCRIXVBJNpUIcYMsjhfsVBDoc+zX9YfmdD2iQmqhjrynEapAaz4XGkslYlaltVC45pDHkCdkMD4gyaniYg=
  template:
    metadata:
      name: database-credentials
      namespace: invidious
    type: kubernetes.io/basic-auth
